/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AffordableCareRouteImport } from './routes/affordable-care'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProviderProviderIdRouteImport } from './routes/provider.$providerId'
import { Route as SchemesIndexRouteImport } from './routes/schemes.index'
import { Route as SchemesSchemeIdRouteImport } from './routes/schemes.$schemeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AffordableCareRoute = AffordableCareRouteImport.update({
  id: '/affordable-care',
  path: '/affordable-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderProviderIdRoute = ProviderProviderIdRouteImport.update({
  id: '/provider/$providerId',
  path: '/provider/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesIndexRoute = SchemesIndexRouteImport.update({
  id: '/schemes/',
  path: '/schemes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesSchemeIdRoute = SchemesSchemeIdRouteImport.update({
  id: '/schemes/$schemeId',
  path: '/schemes/$schemeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affordable-care': typeof AffordableCareRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/nearby': typeof NearbyRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/provider/$providerId': typeof ProviderProviderIdRoute
  '/schemes/$schemeId': typeof SchemesSchemeIdRoute
  '/schemes/': typeof SchemesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affordable-care': typeof AffordableCareRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/nearby': typeof NearbyRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/provider/$providerId': typeof ProviderProviderIdRoute
  '/schemes/$schemeId': typeof SchemesSchemeIdRoute
  '/schemes': typeof SchemesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affordable-care': typeof AffordableCareRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/nearby': typeof NearbyRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/provider/$providerId': typeof ProviderProviderIdRoute
  '/schemes/$schemeId': typeof SchemesSchemeIdRoute
  '/schemes/': typeof SchemesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affordable-care'
    | '/contact'
    | '/explore'
    | '/learn'
    | '/login'
    | '/nearby'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/services'
    | '/signup'
    | '/support'
    | '/terms'
    | '/provider/$providerId'
    | '/schemes/$schemeId'
    | '/schemes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affordable-care'
    | '/contact'
    | '/explore'
    | '/learn'
    | '/login'
    | '/nearby'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/services'
    | '/signup'
    | '/support'
    | '/terms'
    | '/provider/$providerId'
    | '/schemes/$schemeId'
    | '/schemes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affordable-care'
    | '/contact'
    | '/explore'
    | '/learn'
    | '/login'
    | '/nearby'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/services'
    | '/signup'
    | '/support'
    | '/terms'
    | '/provider/$providerId'
    | '/schemes/$schemeId'
    | '/schemes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffordableCareRoute: typeof AffordableCareRoute
  ContactRoute: typeof ContactRoute
  ExploreRoute: typeof ExploreRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  NearbyRoute: typeof NearbyRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ProviderProviderIdRoute: typeof ProviderProviderIdRoute
  SchemesSchemeIdRoute: typeof SchemesSchemeIdRoute
  SchemesIndexRoute: typeof SchemesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affordable-care': {
      id: '/affordable-care'
      path: '/affordable-care'
      fullPath: '/affordable-care'
      preLoaderRoute: typeof AffordableCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$providerId': {
      id: '/provider/$providerId'
      path: '/provider/$providerId'
      fullPath: '/provider/$providerId'
      preLoaderRoute: typeof ProviderProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/': {
      id: '/schemes/'
      path: '/schemes'
      fullPath: '/schemes/'
      preLoaderRoute: typeof SchemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/$schemeId': {
      id: '/schemes/$schemeId'
      path: '/schemes/$schemeId'
      fullPath: '/schemes/$schemeId'
      preLoaderRoute: typeof SchemesSchemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffordableCareRoute: AffordableCareRoute,
  ContactRoute: ContactRoute,
  ExploreRoute: ExploreRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  NearbyRoute: NearbyRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ProviderProviderIdRoute: ProviderProviderIdRoute,
  SchemesSchemeIdRoute: SchemesSchemeIdRoute,
  SchemesIndexRoute: SchemesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
